packages:
  - packages/*
  - apps/*

catalogs:
  build:
    '@rslib/core': ^0.18.6
  prod:
    '@effect/ai': ^0.33.0
    '@effect/platform': ^0.94.0
    '@effect/platform-bun': ^0.87.0
    '@effect/rpc': ^0.73.0
    effect: ^3.19.13
  quality:
    is-tree-shakable: ^0.4.2
    publint: ^0.3.16
  tooling:
    '@effect/language-service': ^0.65.0
  types:
    '@types/bun': ^1.3.5
    typescript: ^5.9.3

patchedDependencies:
  '@effect-native/bun-test': patches/@effect-native__bun-test.patch
