packages:
  - "packages/*"
  - "apps/*"

catalogs:
  # Runtime dependencies shipped to consumers/apps
  prod:
    effect: ^3.19.13
    "@effect/ai": ^0.33.0
    "@effect/platform": ^0.94.0
    "@effect/platform-bun": ^0.87.0
    "@effect/rpc": ^0.73.0
  # Build tooling for libraries
  build:
    "@rslib/core": ^0.18.6
  # Package quality checks
  quality:
    publint: ^0.3.16
    is-tree-shakable: ^0.4.2
  test:
    vitest: ^4.0.16
  # Type tooling
  types:
    typescript: ^5.9.3
    "@types/bun": ^1.3.5
  # Effect-specific tooling
  tooling:
    "@effect/language-service": ^0.62.5
